title: ISSAERIUM 21
author: Issadeen
email: issadeenabdiali@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  ISSAERIUM 2Q is an upcoming tech company which aims to aid people in differet aspects of life

# social links
twitter_username: isserium-21 # DO NOT include the @ character, or else the build will fail!
github_username:  issadeen # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
